version: '3.8'

services:
  clickhouse:
    image: clickhouse/clickhouse-server:23.12
    hostname: clickhouse
    ports:
      - "8123:8123"  # HTTP interface
      - "9000:9000"  # Native interface
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - ./clickhouse-config:/etc/clickhouse-server/config.d
      - ./init-scripts:/docker-entrypoint-initdb.d
    environment:
      CLICKHOUSE_DB: coal_mining
      CLICKHOUSE_USER: default
      CLICKHOUSE_PASSWORD: password
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    networks:
      - coal_mining_network

  metabase:
    image: metabase/metabase:v0.47.7
    hostname: metabase
    ports:
      - "3000:3000"
    volumes:
      - metabase_data:/metabase-data
    environment:
      MB_DB_TYPE: h2
      MB_DB_FILE: /metabase-data/metabase.db
      JAVA_OPTS: "-Xmx2g"
    depends_on:
      - clickhouse
    networks:
      - coal_mining_network

  etl_runner:
    build:
      context: .
      dockerfile: Dockerfile.etl
    volumes:
      - .:/app
      - ./logs:/app/logs
    environment:
      CLICKHOUSE_HOST: clickhouse
      CLICKHOUSE_PORT: 8123
      CLICKHOUSE_USER: default
      CLICKHOUSE_PASSWORD: password
      CLICKHOUSE_DB: coal_mining
    depends_on:
      - clickhouse
    networks:
      - coal_mining_network
    command: >
      sh -c "
        echo 'Waiting for ClickHouse to be ready...' &&
        sleep 30 &&
        python etl_pipeline.py
      "

volumes:
  clickhouse_data:
  metabase_data:

networks:
  coal_mining_network:
    driver: bridge
